name: Deploy Jekyll Site to Pages

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # 使用一个合适的 Ruby 版本
          bundler-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate Navigation Data
        run: python build.py

      - name: Build site with Jekyll
        run: bundle exec jekyll build --config _config.yml,_config_github.yml
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site